### ISSUE TITLE
Errors facing when trying to replicate the simulation.

### ISSUE THREAD

**Issue by nzlz** [AcutronicRobotics/MARA#1]
Hi, Im trying to replicate the work and my first goal is to spawn the MARA in gazebo. Before I start, my current setup is:

- gazebo 9.5.0
- ROS2 Crystal Clemmys - Pre-release (latest from source)

## Dependencies and fixes
Basic things I had to fix/change during the installation:

- **dependency** `https://github.com/erlerobot/control_msgs` is not a public repo, so I used `https://github.com/ros-controls/control_msgs -b bouncy-devel` instead.
- **dependency** git clone https://github.com/ros-perception/vision_opencv.git -b ros2
- **dependency** sudo apt install python3-numpy
- remove all comas "," in [this line](https://github.com/AcutronicRobotics/MARA/blob/fc93557596f1260fa5ce630b9bab41fa2edc5102/mara_description/urdf/mara_robot_camera_top.urdf#L559), leaving it this way: `<origin rpy="0 0 0" xyz="-0.0002009  0.0396149 -0.0161363"/>`.
- update absolute path in call to urdf in `/mara_utils_scripts/spawn_entity.py` and `/mara_utils_scripts/spawn_model.py` . 

Some error output. ws build, fixed urdf and rviz2 related: [gist](https://gist.github.com/nzlz/0c6bb3a3adb32577b2cb5b91aca2981c). 

## Error during the MARA spawn process in gazebo.
Once gazebo is launched (no errors), I execute `spawn_entity.py` but the MARA is not being loaded. The output error is available in this [gist](https://gist.github.com/nzlz/68733d41c519a752a24bf81ae981cb17). I will keep working on this tomorrow.

**Comment by ahcorde** [comment]
Thanks for you feedback @nzlz 

 - I included all the dependencies that were missing. https://github.com/AcutronicRobotics/MARA/commit/03a13e4148f0b4d23b58d46c861be4899075f5c5
 - I removed the comas in the URDF, I think this is a problem of xacro. I will have a look on this. https://github.com/AcutronicRobotics/MARA/commit/2b905bd6417387cb53d1013d2066824a37556ee7
 - Fixed the problem with `spawn_entity` right now we will make use of ros2pkg to find the right path https://github.com/AcutronicRobotics/MARA/commit/321a80087d887ab3989ab04f6655cd3e9cf7b326

**Comment by nzlz** [comment]
## Updates
First of all I just made a [PR](https://github.com/AcutronicRobotics/MARA/pull/2) containing a some small fixes.

Now I manage to spawn the MARA in gazebo. :+1: But in the end, I get a gazebo plugin related issue:
`[Err] [Plugin.hh:180] Failed to load plugin libgazebo_grasp_fix.so: libgazebo_grasp_fix.so: cannot open shared object file: No such file or directory`

**libgazebo_grasp_fix.so** is missing. Ive found it in [JenniferBuehler/gazebo-pkgs](https://github.com/JenniferBuehler/gazebo-pkgs) but it uses the old catkin make. So its not compatible with the ros2 colcon build I believe. Any advice on this? I guess you have already ported the pkg somehow, or you use the ros1-brigde?

**Comment by ahcorde** [comment]
For now we don't need to grasp things. Near future to do task

**Comment by nzlz** [comment]
Everything working fine then. Just commented the `libgazebo_grasp_fix.so` [plugin block](https://github.com/AcutronicRobotics/MARA/blob/5700e95b726958fa888773002a30f61175045965/mara_description/urdf/mara_robot_camera_top.urdf#L675-L691).
 `mara_joint_control.py` is able to move the robot too. 
Closing.
