### ISSUE TITLE
hrim_actuation vs hrm_actuator

### ISSUE THREAD

**Issue by ahcorde** [AcutronicRobotics/MARA#100]
I can still find `hros_actuation` for example here:

https://github.com/AcutronicRobotics/MARA/blob/master/mara_description/urdf/mara_robot_gripper_140_no_table.urdf#L438

Can we fix this? @YueErro ? @nzlz

**Comment by YueErro** [comment]
We can proceed to make the PR of [acutator branch](https://github.com/AcutronicRobotics/MARA/tree/actuator) which updates all the namings.

**Comment by YueErro** [comment]
https://github.com/AcutronicRobotics/MARA/pull/102
