### ISSUE TITLE
Instalation

### ISSUE THREAD

**Issue by naranaa** [AcutronicRobotics/MARA#15]
When I am trying to install MARA (Ros-2) with Gazebo (Ros-1) executing the next instruction  (/opt/ros/crystal/setup.bash) there is no such a folder (crystal). 

In principle ROS2 (Crystal x86) was installed as it is explained in https://index.ros.org/doc/ros2/Installation/Linux-Install-Binary/. And their examples seems to work correctly.

Can you help me?

**Comment by ahcorde** [comment]
this instructions install ROS 2 in `~/ros2_install`. Try to replace:

```
source /opt/ros/crystal/setup.bash
```

with 

```
source ~/ros2_install
```

**Comment by naranaa** [comment]
Thank you.

during the next instruction (https://github.com/AcutronicRobotics/MARA#compile) `cd ~/ros2_mara_ws && colcon build --merge-install ` I have an issue, because it seems that is not able to compile. 
-------------------------------------------------------------------
Starting >>> hrim_generic_msgs
Starting >>> gazebo_dev
Starting >>> gazebo_msgs
Starting >>> camera_calibration_parsers
Starting >>> cv_bridge
Starting >>> image_transport
Starting >>> control_msgs
Starting >>> hrim_actuator_gripper_srvs
--- stderr: image_transport                                            
CMake Error at CMakeLists.txt:60 (pluginlib_export_plugin_description_file):
  Unknown CMake command "pluginlib_export_plugin_description_file".
---
Failed   <<< image_transport	[ Exited with code 1 ]
Aborted  <<< gazebo_dev
Aborted  <<< camera_calibration_parsers          
Aborted  <<< hrim_actuator_gripper_srvs          
Aborted  <<< hrim_generic_msgs
Aborted  <<< control_msgs                                                   
--- stderr: cv_bridge                                                       
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:1626 (message):
  No header defined for python3; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:24 (find_package)

---
Aborted  <<< cv_bridge
Aborted  <<< gazebo_msgs                                    

Summary: 0 packages finished [5.31s]
  1 package failed: image_transport
  7 packages aborted: camera_calibration_parsers control_msgs cv_bridge gazebo_dev gazebo_msgs hrim_actuator_gripper_srvs hrim_generic_msgs
  2 packages had stderr output: cv_bridge image_transport
  19 packages not processed
-------------------------------------------------------------------

**Comment by naranaa** [comment]
ROS2 : ros2-crystal-20181214-linux-bionic-x86_64.tar.bz2
ROS1: Mellodic

**Comment by naranaa** [comment]
I verified if `sensor_msgs` is installed and I would say that it is
 `find . -name "image.hpp"`
`./ros2_install/ros2-linux/include/sensor_msgs/msg/image.hpp`

**Comment by naranaa** [comment]
I did one step back to try to install ROS2 from the sources https://index.ros.org/doc/ros2/Installation/Linux-Development-Setup/.  When I try to build the code in the workspace 

`colcon build --symlink-install`

I have the next error. Do you know why?

...
Starting >>> rosidl_typesupport_cpp                    
Finished <<< rosidl_typesupport_cpp [0.55s]                            
--- stderr: rosidl_generator_py                                  
/usr/bin/ld: cannot find -lrosidl_generator_py_custom__rosidl_typesupport_opensplice_c
collect2: error: ld returned 1 exit status
make[2]: *** [rosidl_generator_py/rosidl_generator_py/rosidl_generator_py_s__rosidl_typesupport_opensplice_c.cpython-36m-x86_64-linux-gnu.so] Error 1
make[1]: *** [CMakeFiles/rosidl_generator_py__rosidl_typesupport_opensplice_c__pyext.dir/all] Error 2
make: *** [all] Error 2

Failed   <<< rosidl_generator_py	[ Exited with code 2 ]

Summary: 120 packages finished [19.8s]
  1 package failed: rosidl_generator_py
  1 package had stderr output: rosidl_generator_py
  107 packages not processed

**Comment by nzlz** [comment]
If you are using Ubuntu18, I suggest you follow the [debian packages installation](https://index.ros.org/doc/ros2/Installation/Linux-Install-Debians/), you will find a much easier installation. If not, you should ask about your error at https://answers.ros.org/questions/.

**Comment by naranaa** [comment]
I just install it from [debian packages installation](https://index.ros.org/doc/ros2/Installation/Linux-Install-Debians/) packages, 

but when I come back to the compilation step (https://github.com/AcutronicRobotics/MARA)

`cd ~/ros2_mara_ws && colcon build --merge-install`

it does not work due to the next error

`fatal error: sensor_msgs/msg/image.hpp: No such file or directory`

but doing 

`ls ./ros2_install/ros2-linux/include/sensor_msgs/msg/image.hpp `

I can see that it exist 

`./ros2_install/ros2-linux/include/sensor_msgs/msg/image.hpp`

/............................................................................................./
Starting >>> hrim_generic_msgs
Starting >>> gazebo_dev
Starting >>> gazebo_msgs
Starting >>> camera_calibration_parsers
Starting >>> cv_bridge
Starting >>> image_transport
Starting >>> control_msgs
Starting >>> hrim_actuator_gripper_srvs
--- stderr: cv_bridge                                                     
In file included from /home/robotlab/ros2_mara_ws/src/vision_opencv/cv_bridge/src/cv_bridge.cpp:37:0:
/home/robotlab/ros2_mara_ws/src/vision_opencv/cv_bridge/include/cv_bridge/cv_bridge.h:40:10: fatal error: sensor_msgs/msg/image.hpp: No such file or directory
 #include <sensor_msgs/msg/image.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/cv_bridge.dir/cv_bridge.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/cv_bridge.dir/all] Error 2
make: *** [all] Error 2

Failed   <<< cv_bridge	[ Exited with code 2 ]
Aborted  <<< camera_calibration_parsers          
Aborted  <<< gazebo_dev                          
--- stderr: image_transport                      
CMake Error at CMakeLists.txt:60 (pluginlib_export_plugin_description_file):
  Unknown CMake command "pluginlib_export_plugin_description_file".


---
Aborted  <<< image_transport
--- stderr: gazebo_msgs
Message interface 'geometry_msgs/Wrench' contains an unknown field type: geometry_msgs/Wrench[] wrenches
Message interface 'geometry_msgs/Wrench' contains an unknown field type: geometry_msgs/Wrench[] wrenches
make[2]: *** [rosidl_typesupport_cpp/gazebo_msgs/msg/contact_state__type_support.cpp] Error 1
make[1]: *** [CMakeFiles/gazebo_msgs__rosidl_typesupport_cpp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [rosidl_typesupport_introspection_cpp/gazebo_msgs/msg/contact_state__rosidl_typesupport_introspection_cpp.hpp] Error 1
make[1]: *** [CMakeFiles/gazebo_msgs__rosidl_typesupport_introspection_cpp.dir/all] Error 2
Message interface 'geometry_msgs/Wrench' contains an unknown field type: geometry_msgs/Wrench[] wrenches
make[2]: *** [rosidl_typesupport_fastrtps_cpp/gazebo_msgs/msg/contact_state__rosidl_typesupport_fastrtps_cpp.hpp] Error 1
make[1]: *** [CMakeFiles/gazebo_msgs__rosidl_typesupport_fastrtps_cpp.dir/all] Error 2
Message interface 'geometry_msgs/Wrench' contains an unknown field type: geometry_msgs/Wrench[] wrenches
make[2]: *** [rosidl_typesupport_c/gazebo_msgs/msg/contact_state__type_support.cpp] Error 1
make[1]: *** [CMakeFiles/gazebo_msgs__rosidl_typesupport_c.dir/all] Error 2
Message interface 'geometry_msgs/Wrench' contains an unknown field type: geometry_msgs/Wrench[] wrenches
Message interface 'geometry_msgs/Wrench' contains an unknown field type: geometry_msgs/Wrench[] wrenches
make[2]: *** [rosidl_typesupport_connext_cpp/gazebo_msgs/msg/contact_state__rosidl_typesupport_connext_cpp.hpp] Error 1
make[1]: *** [CMakeFiles/gazebo_msgs__rosidl_typesupport_connext_cpp.dir/all] Error 2
make[2]: *** [rosidl_typesupport_introspection_c/gazebo_msgs/msg/contact_state__rosidl_typesupport_introspection_c.h] Error 1
make[1]: *** [CMakeFiles/gazebo_msgs__rosidl_typesupport_introspection_c.dir/all] Error 2
make: *** [all] Error 2

Aborted  <<< gazebo_msgs
--- stderr: control_msgs                         
Message interface 'std_msgs/Header' contains an unknown field type: std_msgs/Header header
make[2]: *** [rosidl_typesupport_c/control_msgs/msg/gripper_command__type_support.cpp] Error 1
make[2]: *** Deleting file 'rosidl_typesupport_c/control_msgs/msg/gripper_command__type_support.cpp'
make[1]: *** [CMakeFiles/control_msgs__rosidl_typesupport_c.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Message interface 'std_msgs/Header' contains an unknown field type: std_msgs/Header header
make[2]: *** [rosidl_typesupport_cpp/control_msgs/msg/gripper_command__type_support.cpp] Error 1
make[2]: *** Deleting file 'rosidl_typesupport_cpp/control_msgs/msg/gripper_command__type_support.cpp'
make[1]: *** [CMakeFiles/control_msgs__rosidl_typesupport_cpp.dir/all] Error 2
Message interface 'std_msgs/Header' contains an unknown field type: std_msgs/Header header
make[2]: *** [rosidl_typesupport_connext_cpp/control_msgs/msg/gripper_command__rosidl_typesupport_connext_cpp.hpp] Error 1
make[2]: *** Deleting file 'rosidl_typesupport_connext_cpp/control_msgs/msg/gripper_command__rosidl_typesupport_connext_cpp.hpp'
make[1]: *** [CMakeFiles/control_msgs__rosidl_typesupport_connext_cpp.dir/all] Error 2
Message interface 'std_msgs/Header' contains an unknown field type: std_msgs/Header header
Message interface 'std_msgs/Header' contains an unknown field type: std_msgs/Header header
make[2]: *** [rosidl_typesupport_fastrtps_cpp/control_msgs/msg/gripper_command__rosidl_typesupport_fastrtps_cpp.hpp] Error 1
make[2]: *** Deleting file 'rosidl_typesupport_fastrtps_cpp/control_msgs/msg/gripper_command__rosidl_typesupport_fastrtps_cpp.hpp'
make[1]: *** [CMakeFiles/control_msgs__rosidl_typesupport_fastrtps_cpp.dir/all] Error 2
make[2]: *** [rosidl_typesupport_introspection_cpp/control_msgs/msg/gripper_command__rosidl_typesupport_introspection_cpp.hpp] Error 1
make[2]: *** Deleting file 'rosidl_typesupport_introspection_cpp/control_msgs/msg/gripper_command__rosidl_typesupport_introspection_cpp.hpp'
make[1]: *** [CMakeFiles/control_msgs__rosidl_typesupport_introspection_cpp.dir/all] Error 2
Message interface 'std_msgs/Header' contains an unknown field type: std_msgs/Header header
make[2]: *** [rosidl_typesupport_introspection_c/control_msgs/msg/gripper_command__rosidl_typesupport_introspection_c.h] Error 1
make[2]: *** Deleting file 'rosidl_typesupport_introspection_c/control_msgs/msg/gripper_command__rosidl_typesupport_introspection_c.h'
make[1]: *** [CMakeFiles/control_msgs__rosidl_typesupport_introspection_c.dir/all] Error 2
make: *** [all] Error 2

Aborted  <<< control_msgs
Aborted  <<< hrim_actuator_gripper_srvs
Aborted  <<< hrim_generic_msgs                                         

Summary: 0 packages finished [1.49s]
  1 package failed: cv_bridge
  7 packages aborted: camera_calibration_parsers control_msgs gazebo_dev gazebo_msgs hrim_actuator_gripper_srvs hrim_generic_msgs image_transport
  4 packages had stderr output: control_msgs cv_bridge gazebo_msgs image_transport
  19 packages not processed

**Comment by nzlz** [comment]
Just checked that the instructions are correct. So I recommend you do the following:
1. Open a new terminal and only source /opt/ros/crystal/setup.bash . Check that bashrc is not sourcing other workspaces.
2. Check that you followed the instructions correctly, specially [this](https://github.com/AcutronicRobotics/MARA#create-mara-ros-20-workspace) part.
3. Source ROS2 + compile. Note: 
```
 source /opt/ros/crystal/setup.bash
cd ~/ros2_mara_ws && colcon build --merge-install
```

Please make sure you are not mixing ROS distributions and that you are only sourcing ROS2 at this stage.

**Comment by naranaa** [comment]
1. After doing the first step I checked that there is no reference to other ROS environment (in my case Melodic) in `.bashrc` and `env`. 
2. I check that I am following the [instructions](https://github.com/AcutronicRobotics/MARA#create-mara-ros-20-workspace)
3. But still I have the same problem while compiling
```
source /opt/ros/crystal/setup.bash
cd ~/ros2_mara_ws && colcon build --merge-install
```

**Comment by ahcorde** [comment]
can you check that in your `~/.bashrc` you are not sourcing ros1?

if so, please remove the line

```
source /opt/ros/kinetic/setup.bash
```

or `melodic`, it depends on your installation

**Comment by naranaa** [comment]
Yes, I did in the previous step, It was already removed. 

I decided to start from zero and to install only Ros2-crystal (from Debian package) in Ubuntu 18.0.4. 

If another configuration is better, please let me know.

**Comment by naranaa** [comment]
Installing only ROS2 is ok, except the packages related with Ros1. Let s install ROS1.

Failed   <<< gazebo_ros	[ Exited with code 1 ]

Summary: 22 packages finished [3min 13s]
  1 package failed: gazebo_ros
  2 packages had stderr output: cv_bridge gazebo_ros
  4 packages not processed

**Comment by naranaa** [comment]
Thanks to your feedback I am moving forwards. I am already able to see the robot in Gazebo. 

Right now I am trying to execute the moveIT bridge, where I found the next error in one of the terminal, while the other terminal seems to work properly.

ros2 run individual_trajectories_bridge individual_trajectories_bridge -motors `ros2 pkg prefix individual_trajectories_bridge`/share/individual_trajectories_bridge/motors.yaml

> No executable found

**Comment by ahcorde** [comment]
This executable is a bridge. It makes the conversion between ROS 2.0 and ROS worlds. To be able to use MoveIT!. Try this:

```
source ~/ros2_mara_ws/install/setup.bash
source /opt/ros/melodic/setup.bash

cd ~/ros2_mara_ws/
rm -r build/individual_trajectories_bridge
colcon build --merge-install --packages-select individual_trajectories_bridge
```

and try again

**Comment by naranaa** [comment]
At the end it give me an error

`source ~/ros2_mara_ws/install/setup.bash`

`source /opt/ros/melodic/setup.bash`

ROS_DISTRO was set to 'crystal' before. Please make sure that the environment does not mix paths from different distributions.

`cd ~/ros2_mara_ws/`

`rm -r build/individual_trajectories_bridge`

`colcon build --merge-install --packages-select individual_trajectories_bridge`

Starting >>> individual_trajectories_bridge
--- stderr: individual_trajectories_bridge                              
CMakeFiles/individual_trajectories_bridge.dir/src/main.cpp.o: In function `rclcpp::Publisher<trajectory_msgs::msg::JointTrajectory_<std::allocator<void> >, std::allocator<void> >::Publisher(rclcpp::node_interfaces::NodeBaseInterface*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_publisher_options_t const&, std::shared_ptr<std::allocator<trajectory_msgs::msg::JointTrajectory_<std::allocator<void> > > > const&)':
/opt/ros/crystal/include/rclcpp/publisher.hpp:173: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<trajectory_msgs::msg::JointTrajectory_<std::allocator<void> > >()'
collect2: error: ld returned 1 exit status
make[2]: *** [individual_trajectories_bridge] Error 1
make[1]: *** [CMakeFiles/individual_trajectories_bridge.dir/all] Error 2
make: *** [all] Error 2

Failed   <<< individual_trajectories_bridge	[ Exited with code 2 ]

Summary: 0 packages finished [9.07s]
  1 package failed: individual_trajectories_bridge
  1 package had stderr output: individual_trajectories_bridge

**Comment by ahcorde** [comment]
I pushed yesterday some code https://github.com/AcutronicRobotics/MARA/commit/9c480c485cdbc4748935c95210991fc918e68c6f

Plaese repeat this commands https://github.com/AcutronicRobotics/MARA/issues/15#issuecomment-454850728

**Comment by naranaa** [comment]
Now the compilation works and even the bridge. Thanks.

This time I have an issue launching MoveIT (Terminal 3)

`source ~/ros_mara_ws/install_isolated/setup.bash`

`roslaunch mara_moveit_config mara_moveit_planning_execution.launch`

...................................................
...
NODES
  /
    move_group (moveit_ros_move_group/move_group)

ROS_MASTER_URI=http://localhost:11311

ERROR: cannot launch node of type [moveit_ros_move_group/move_group]: moveit_ros_move_group
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/robotlab/ros_mara_ws/install_isolated/share
ROS path [2]=/opt/ros/melodic/share
No processes to monitor
shutting down processing monitor...
... shutting down processing monitor complete

**Comment by ahcorde** [comment]
you need to install `ros-melodic-moveit-ros-move-group`

**Comment by naranaa** [comment]
Thank you very much, everything seems to work properly. I would like to thanks to you and your team for this fantastic support.

**Comment by ardabbour** [comment]
Hello, just a heads-up that [#15 (comment)](https://github.com/AcutronicRobotics/MARA/issues/15#issuecomment-454850728) should be in the installation section. I couldn't install without it.

**Comment by LanderU** [comment]
> Hello, just a heads-up that #15 (comment) should be in the installation section. I couldn't install without it.

Thank you, we will add this to the installation instructions.
