### ISSUE TITLE
mara_gripper_hande.launch.py failing

### ISSUE THREAD

**Issue by nzlz** [AcutronicRobotics/MARA#27]
## Bug report

**Required Info:**

- Operating System:
Ubuntu18
- ROS and ROS2 versions:
ROS2 Crystal
- Failing component:
Gazebo RobotiqLinearPlugin.cpp:203
#### Steps to reproduce issue

```
ros2 launch mara_gazebo mara_gripper_hande.launch.py
```
Trace:
```
[Err] [RobotiqLinearPlugin.cpp:203] EXCEPTION: Could not find finger1_joint left joint

[Err] [Model.cc:1129] Exception occured in the Load function of plugin with name[robotiq_hande_gripper] and filename[librobotiq_linear_gripper_gazebo_plugin.so]. This plugin will not run.
```

**Comment by vmayoral** [comment]
Thanks for reporting @nzlz, @ahcorde mind having a look at this?

**Comment by ahcorde** [comment]
fixed https://github.com/AcutronicRobotics/MARA/commit/8836ca90b8c7504362611eb609bc9dfed8ef9d3b
