### ISSUE TITLE
Gripper not responding correctly

### ISSUE THREAD

**Issue by nzlz** [AcutronicRobotics/MARA#51]
## Bug report

**Required Info:**

Ubuntu 18, ROS2 Crystal

**Bug**
The gripper is not working correctly anymore, not sure if the new URDF is causing it or the mara joint plugin. If i spawn the gripper alone the fingers move as expected, but attached to the mara if needs a much higher `goal_linearposition` than the maximum 0.8 limit.

You can reproduce it using:

```bash
ros2 service call /hrim_actuation_gripper_000000000004/goal hrim_actuator_gripper_srvs/ControlFinger "{goal_linearposition: 0.8}"
```

**Comment by nzlz** [comment]
Confirmed that is is a MARA URDF issue. The [previous URDF](https://github.com/AcutronicRobotics/MARA/blob/master/mara_description/urdf/mara_robot_gripper_140.urdf) (updating the plugins to the new), of which we have a backup in the ai branch, works fine.

**Comment by YueErro** [comment]
Yep, there is an issue with the gripper in the current orientation. If you unflipped it, it works fine ([end_effector_adapter_to_robotiq joint](https://github.com/AcutronicRobotics/MARA/blob/master/mara_description/urdf/mara_robot_gripper_140.urdf.xacro#L27)).

If you also flip it in [robotiq_modularripper](https://github.com/AcutronicRobotics/robotiq_modular_gripper/blob/master/robotiq_140_gripper_description/urdf/robotiq_140_hros_support.urdf.xacro#L39) to spaw it alone, it also stops working properly.

Not sure if it is urdf issue, i do not see anything weird. Maybe the inertia values?

_hros_robotiq_adapter is also 1.57 flipped in yaw, anyhow, this does not affect the open/close action of the gripper_

**Comment by nzlz** [comment]
Can confirm what @YueErro said, the following change fixes the issue:

```diff
  <joint name="end_effector_adapter_to_robotiq" type="fixed">
-    <origin rpy="0 0 1.57" xyz=" 0 0 0.0"/>
+    <origin rpy="0 0 0" xyz=" 0 0 0.0"/>
```

**Comment by YueErro** [comment]
I can not understand the logic behind this which make the gripper stop closing.

The gripper should work fine in any orientation. In our particular case, to match with the real robot, we need to flip it as it is right now, 1.57 in yaw.

**Comment by ahcorde** [comment]
try to rotate only the visual and the collision

**Comment by YueErro** [comment]
Already tried it. Did not work.

**Comment by nzlz** [comment]
Will discuss internally.
