### ISSUE TITLE
mara-ros2.repos

### ISSUE THREAD

**Issue by YueErro** [AcutronicRobotics/MARA#97]
Status:
- [gazebo_ros_pkgs](https://github.com/AcutronicRobotics/MARA/blob/master/mara-ros2.repos#L18-L21), [image_common](https://github.com/AcutronicRobotics/MARA/blob/master/mara-ros2.repos#L30-L33) and [vision_opencv](https://github.com/AcutronicRobotics/MARA/blob/master/mara-ros2.repos#L34-L37) can be installed from deb.
- The compilation of **[geometry2](https://github.com/AcutronicRobotics/MARA/blob/master/mara-ros2.repos#L26-L29) is failing**.
- [control_msgs](https://github.com/AcutronicRobotics/MARA/blob/master/mara-ros2.repos#L22-L25) is needed till they fix it. Related issue https://github.com/AcutronicRobotics/MARA/issues/92.

**Comment by LanderU** [comment]
> The compilation of geometry2 is failing.

Is not longer needed. I will update all the infrastructure to be fully compliant.

**Comment by rkojcev** [comment]
> The compilation of geometry2 is failing.

You do not need that as well is in ros2 dashing installation. But good to double check

**Comment by rkojcev** [comment]
https://github.com/AcutronicRobotics/MARA/pull/99
